#!/usr/bin/env sh
# go options - from go-workspace makefile
# this Makefile is assumed to run in a $GOPATH workspace
export GOPATH=$HOME/code/go-workspace
# the go target below ensures that this is a valid assumption
export GOROOT=$GOPATH/go
# add the verified go toolchain to the front of the path: go, gofmt, goimports, etc
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

# adding other randos
export PATH=:/usr/local/opt/coreutils/libexec/gnubin:/opt/chefdk/bin:$PATH

## source cinderella bash completions
if [[ -d "$HOME/etc/bash_completion.d" ]] ; then
    source $HOME/etc/bash_completion.d/*.bash
fi

## Set ls options per platform
alias ls='ls -p --color=auto'

## Functions
function parse_git_dirty {
  [[ $(git status 2> /dev/null | tail -n1) != *"nothing to commit"* ]] && echo "*"
}
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}

## Prompt
if [[ -n "${SSH_CONNECTION+x}" ]]; then
  export PS1="\H:\W \$(parse_git_branch)\$ "
else
  export PS1="\W \$(parse_git_branch)\$ "
fi

if [[ -s $(which keychain 2>/dev/null) ]]; then
  keychain ~/.ssh/id_rsa
fi

# chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh
chruby ruby

# added by travis gem
[ -f /Users/inessombra/.travis/travis.sh ] && source /Users/inessombra/.travis/travis.sh

# hub configs
eval "$(hub alias -s)"
export FASTLY_USERNAME='randommood'
